/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.Panels;

import DTOs.HistorialVentaDTO;
import Excepciones.BOException;
import Negocio.HistorialVentaBO;
import Singletone.Singletone;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author skevi
 */
public class PnlSalesHistory extends javax.swing.JPanel {


    private int limit;
    private int offset;
    private HistorialVentaBO hvBO;
    Singletone single;
    
    public PnlSalesHistory() {
        initComponents();
        this.hvBO = new HistorialVentaBO();
        this.single = new Singletone();
        
        this.limit = 11;
        this.offset = 0;
        setList();
       
        this.btnPrevio.setVisible(false);
    }
    
    
    private void setList(){
       try{
        int id = Integer.parseInt(single.getPersona().getId());
        
        List<HistorialVentaDTO> historialVentas = hvBO.
                obtenerHistorialVentasPaginado(id, limit, offset);
        
           if (historialVentas.size() < 11) {
               this.btnSiguiente.setVisible(false);
               this.lblPagina.setVisible(false);
           }
        
        // Definir los nombres de las columnas para la tabla
        String[] columnas = {"Vendedor", "Comprador", "Boleto", "Precio Venta", "Fecha Venta", "Hora Venta"};

        // Crear un modelo de tabla con las columnas
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);

        // Recorrer la lista de historial de ventas
        for (HistorialVentaDTO historialVenta : historialVentas) {
            // Extraer los datos de cada objeto HistorialVentaDTO
            String comprador = historialVenta.getComprador().getNombre(); 
            String evento = historialVenta.getBoleto().getEvento().getNombre(); 
            BigDecimal precioVenta = historialVenta.getPrecio_venta();
            Date fechaVenta = (Date) historialVenta.getFecha_venta();
            Time horaVenta = historialVenta.getHora_venta();

            // Crear una fila con los datos extraídos
            Object[] fila = {id, comprador, evento, precioVenta, fechaVenta, horaVenta};

            // Agregar la fila al modelo de la tabla
            modeloTabla.addRow(fila);
        }

        // Asignar el modelo a la tabla (tblHistorialVenta)
        tblVentas.setModel(modeloTabla);
       }
       catch(BOException ex){
           JOptionPane.showMessageDialog(this, ex.getMessage());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        lblPagina = new javax.swing.JLabel();
        btnPrevio = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        lblPagina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPagina.setText("1");

        btnPrevio.setText("Previo");

        btnSiguiente.setText("Siguiente");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Historial de ventas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(btnPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPagina)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevio;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPagina;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
