/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.Panels;

import DTOs.HistorialCompraDTO;
import Excepciones.BOException;
import Negocio.HistorialCompraBO;
import Singletone.Singletone;
import java.sql.Date;
import java.sql.Time;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author skevi
 */
public class PnlShoppingHistory extends javax.swing.JPanel {

    private int limit;
    private int offset;
    
    Singletone single;
    HistorialCompraBO hcBO;
    
    public PnlShoppingHistory() {
        initComponents();
        this.hcBO = new HistorialCompraBO();
        this.single = new Singletone(); 
        
        this.limit = 11;
        this.offset = 0;
        
        tablaHistorialCompras();
        
        this.btnPrevio.setVisible(false);
    }

    private void tablaHistorialCompras() {
        try{
        
        int id = Integer.parseInt(single.getPersona().getId());
            
        List<HistorialCompraDTO> historialCompras =  hcBO.
                obtenerHistorialComprasPaginado(id, limit, offset);
            
            if (historialCompras.size() < 11) {
                this.btnSiguiente.setVisible(false);
                this.lblPagina.setVisible(false);
            }
        
        // Definir los nombres de las columnas de la tabla
        String[] columnas = {"Boleto", "Fecha Compra", "Hora Compra", 
            "Tipo Compra"};

        // Crear un modelo de tabla con las columnas
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);

        // Recorrer la lista de historial de compras
        for (HistorialCompraDTO historialCompra : historialCompras) {
            // Extraer los datos de cada objeto HistorialCompraDTO
            String evento = historialCompra.getBoleto().getEvento().getNombre(); 
            String fila = historialCompra.getBoleto().getFila();
            String asiento  = historialCompra.getBoleto().getAsiento();
            Date fechaCompra = historialCompra.getFecha_compra();
            Time horaCompra = historialCompra.getHora_compra();
            String tipoCompra = historialCompra.getTipo_compra();

            // Crear una fila con los datos extraídos
            Object[] object = {evento, fila, asiento, fechaCompra, horaCompra, 
                tipoCompra};

            // Agregar la fila al modelo de la tabla
            modeloTabla.addRow(object);
        }

        // Asignar el modelo a la tabla (tblHistorialCompra)
        tblCompras.setModel(modeloTabla);
        }
        catch(BOException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblPagina = new javax.swing.JLabel();
        btnPrevio = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompras);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Historial de compras");

        lblPagina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagina.setText("1");

        btnPrevio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrevio.setText("Previo");

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(btnPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagina)
                    .addComponent(btnPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevio;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPagina;
    private javax.swing.JTable tblCompras;
    // End of variables declaration//GEN-END:variables
}
